const PROJECTS = {
  codelens: {
    name: "RVM.CodeLens",
    number: "#01",
    tagline: "Ferramenta de analise estatica para solucoes .NET usando Roslyn, com CLI, dashboard Blazor e API REST.",
    tagline_en: "Static analysis tool for .NET solutions using Roslyn, with CLI, Blazor dashboard and REST API.",
    icon: "\ud83d\udd0d",
    color: "#58a6ff",
    tests: 34,
    repo: "https://github.com/Elfarrar/RVM.CodeLens",
    demo: "https://codelens.lab.rvmtech.com.br",
    tags: ["Roslyn", "CLI", "Blazor", "REST API", "Static Analysis"],
    description: `RVM.CodeLens e uma ferramenta de analise estatica que utiliza o compilador Roslyn para calcular metricas de codigo, detectar padroes arquiteturais, mapear dependencias e identificar hotspots atraves da analise de historico Git. O projeto oferece tres interfaces: uma CLI com multiplos formatos de saida (tabela, JSON, Markdown), um dashboard web Blazor Server com visualizacoes interativas e uma API REST para integracao com outras ferramentas.`,
    description_en: `RVM.CodeLens is a static analysis tool that uses the Roslyn compiler to calculate code metrics, detect architectural patterns, map dependencies and identify hotspots through Git history analysis. The project offers three interfaces: a CLI with multiple output formats (table, JSON, Markdown), a Blazor Server web dashboard with interactive visualizations and a REST API for integration with other tools.`,
    features: [
      "Calculo de Complexidade Ciclomatica (CC) com suporte a if, for, switch, catch, operadores logicos e ternarios",
      "Indice de Manutenibilidade (MI) usando a formula do Visual Studio",
      "Acoplamento de classes via analise semantica do Roslyn",
      "Profundidade de heranca e contagem de linhas (codigo, comentarios, em branco)",
      "Grafo de dependencias entre projetos e pacotes NuGet",
      "Deteccao automatica de camadas arquiteturais (Domain, Application, Infrastructure, Presentation)",
      "Analise de hotspots combinando churn do Git com complexidade",
      "CLI com Spectre.Console, Dashboard Blazor e 6 endpoints REST",
      "Multiplos formatos de saida: tabela, JSON e Markdown"
    ],
    features_en: [
      "Cyclomatic Complexity (CC) calculation with support for if, for, switch, catch, logical and ternary operators",
      "Maintainability Index (MI) using the Visual Studio formula",
      "Class coupling via Roslyn semantic analysis",
      "Inheritance depth and line counts (code, comments, blank)",
      "Dependency graph between projects and NuGet packages",
      "Automatic detection of architectural layers (Domain, Application, Infrastructure, Presentation)",
      "Hotspot analysis combining Git churn with complexity",
      "CLI with Spectre.Console, Blazor Dashboard and 6 REST endpoints",
      "Multiple output formats: table, JSON and Markdown"
    ],
    technologies: [".NET 10", "Roslyn (Microsoft.CodeAnalysis) 5.3", "MSBuild Workspaces", "LibGit2Sharp", "Spectre.Console", "Blazor Server", "ASP.NET Core", "Serilog", "xUnit", "Moq"],
    patterns: ["Layered Architecture", "Visitor Pattern (SyntaxWalkers)", "Strategy Pattern (Formatters)", "Dependency Injection", "Immutable Models (Records)", "Minimal API (MapGroup)"],
    endpoints: [
      { method: "POST", path: "/api/analyze", desc: "Analisa solucao .NET", desc_en: "Analyze .NET solution" },
      { method: "GET", path: "/api/analysis/current", desc: "Analise carregada em memoria", desc_en: "Current analysis in memory" },
      { method: "GET", path: "/api/metrics", desc: "Metricas de todos os projetos", desc_en: "Metrics for all projects" },
      { method: "GET", path: "/api/deps", desc: "Grafo de dependencias", desc_en: "Dependency graph" },
      { method: "GET", path: "/api/hotspots", desc: "Hotspots baseados em Git", desc_en: "Git-based hotspots" },
      { method: "GET", path: "/api/architecture", desc: "Camadas e violacoes", desc_en: "Layers and violations" }
    ]
  },
  authforge: {
    name: "RVM.AuthForge",
    number: "#02",
    tagline: "Plataforma completa de Identity & Access Management com OAuth2/OIDC, API Key, 2FA e dashboard admin Blazor.",
    tagline_en: "Complete Identity & Access Management platform with OAuth2/OIDC, API Key, 2FA and Blazor admin dashboard.",
    icon: "\ud83d\udd10",
    color: "#d29922",
    tests: 13,
    repo: "https://github.com/Elfarrar/RVM.AuthForge",
    demo: "https://authforge.lab.rvmtech.com.br",
    tags: ["OAuth2/OIDC", "OpenIddict", "2FA", "Blazor", "Identity"],
    description: `RVM.AuthForge e uma plataforma completa de Identity & Access Management (IAM) construida com ASP.NET Core 10 e OpenIddict 7.4. Funciona como servidor de autorizacao centralizado para todo o ecossistema RVM Tech, suportando fluxos OAuth2/OIDC (Authorization Code + PKCE, Client Credentials, Refresh Token), autenticacao por API Key, autenticacao de dois fatores (2FA) com TOTP, auditoria abrangente de acoes e um painel administrativo integrado em Blazor Server.`,
    description_en: `RVM.AuthForge is a complete Identity & Access Management (IAM) platform built with ASP.NET Core 10 and OpenIddict 7.4. It works as a centralized authorization server for the entire RVM Tech ecosystem, supporting OAuth2/OIDC flows (Authorization Code + PKCE, Client Credentials, Refresh Token), API Key authentication, two-factor authentication (2FA) with TOTP, comprehensive action auditing and an integrated Blazor Server admin dashboard.`,
    features: [
      "Servidor OAuth2/OIDC completo com OpenIddict 7.4 (Authorization Code + PKCE, Client Credentials, Refresh Token)",
      "Gerenciamento de usuarios com registro, login, bloqueio apos 5 tentativas, reset de senha",
      "Autenticacao de dois fatores (2FA) com TOTP, QR Code e 10 codigos de recuperacao",
      "API Keys com hash SHA256, validacao e revogacao",
      "Controle de acesso baseado em roles (RBAC) com roles customizaveis",
      "Auditoria completa com 16 tipos de acao, IP, User-Agent e Correlation ID",
      "Dashboard admin Blazor Server com 7 paginas interativas",
      "Suporte a React SPA Portal com cliente publico OAuth2 pre-configurado",
      "Rate limiting (10 req/min) nos endpoints de autenticacao"
    ],
    features_en: [
      "Complete OAuth2/OIDC server with OpenIddict 7.4 (Authorization Code + PKCE, Client Credentials, Refresh Token)",
      "User management with registration, login, lockout after 5 attempts, password reset",
      "Two-factor authentication (2FA) with TOTP, QR Code and 10 recovery codes",
      "API Keys with SHA256 hash, validation and revocation",
      "Role-based access control (RBAC) with customizable roles",
      "Full audit trail with 16 action types, IP, User-Agent and Correlation ID",
      "Blazor Server admin dashboard with 7 interactive pages",
      "React SPA Portal support with pre-configured public OAuth2 client",
      "Rate limiting (10 req/min) on authentication endpoints"
    ],
    technologies: [".NET 10", "ASP.NET Core Identity", "OpenIddict 7.4", "PostgreSQL", "EF Core 10", "Npgsql 10.0.1", "Blazor Server", "Serilog", "xUnit", "Moq"],
    patterns: ["Layered Architecture (Domain/Infrastructure/API)", "Repository Pattern", "Policy-Based Authorization", "Custom Auth Handler Pattern", "Middleware Pipeline", "Configuration-Driven Seed Service"],
    endpoints: [
      { method: "POST", path: "/api/account/register", desc: "Registro de usuario", desc_en: "User registration" },
      { method: "POST", path: "/api/account/login", desc: "Login", desc_en: "Login" },
      { method: "POST", path: "/api/account/2fa/setup", desc: "Configurar 2FA", desc_en: "Setup 2FA" },
      { method: "POST", path: "/connect/authorize", desc: "OAuth2 Authorization", desc_en: "OAuth2 Authorization" },
      { method: "POST", path: "/connect/token", desc: "OAuth2 Token Exchange", desc_en: "OAuth2 Token Exchange" },
      { method: "GET", path: "/api/admin/users", desc: "Listar usuarios (Admin)", desc_en: "List users (Admin)" },
      { method: "POST", path: "/api/admin/api-keys", desc: "Criar API Key", desc_en: "Create API Key" }
    ]
  },
  menunamao: {
    name: "RVM.MenuNaMao",
    number: "#03",
    tagline: "Sistema de cardapio digital com QR Code por mesa, pedidos em tempo real, Mediator customizado e RabbitMQ.",
    tagline_en: "Digital menu system with QR Code per table, real-time orders, custom Mediator and RabbitMQ.",
    icon: "\ud83c\udf7d\ufe0f",
    color: "#f0883e",
    tests: 11,
    repo: "https://github.com/Elfarrar/RVM.MenuNaMao",
    demo: "https://menunamao.lab.rvmtech.com.br",
    tags: ["Clean Architecture", "Mediator", "RabbitMQ", "QR Code", "Blazor", "React"],
    description: `RVM.MenuNaMao e um sistema completo de cardapio digital para restaurantes. Permite que clientes escaneiem QR Codes nas mesas para visualizar o cardapio e fazer pedidos direto do celular. O sistema opera em dois fronts: um painel admin Blazor Server para gerenciar cardapio, pedidos e estoque, e um frontend React SPA para os clientes. Eventos sao propagados de forma assincrona via RabbitMQ. O destaque tecnico e o Mediator Pattern implementado do zero, sem dependencia do MediatR.`,
    description_en: `RVM.MenuNaMao is a complete digital menu system for restaurants. It allows customers to scan QR Codes on tables to view the menu and place orders directly from their phones. The system operates on two fronts: a Blazor Server admin panel for managing menu, orders and inventory, and a React SPA frontend for customers. Events are propagated asynchronously via RabbitMQ. The technical highlight is the Mediator Pattern implemented from scratch, without MediatR dependency.`,
    features: [
      "Suporte multi-restaurante com identificacao por slug unico",
      "Cardapio digital com categorias, itens, precos, imagens e tempo de preparo",
      "Geracao de QR Code por mesa com link direto para o cardapio (QRCoder)",
      "Processamento de pedidos em tempo real do celular ao dashboard admin",
      "Workflow de status: Pending -> Preparing -> Ready -> Delivered / Cancelled",
      "Controle de estoque com movimentacoes (entrada, saida, ajuste) e alertas de estoque baixo",
      "Dashboard operacional com pedidos pendentes, totais diarios e receita",
      "Mediator Pattern customizado com Send/Publish, sem MediatR",
      "Pipeline Behaviors para logging e validacao automatica",
      "Mensageria assincrona via RabbitMQ com publisher e 3 consumers"
    ],
    features_en: [
      "Multi-restaurant support with unique slug identification",
      "Digital menu with categories, items, prices, images and prep time",
      "QR Code generation per table with direct menu link (QRCoder)",
      "Real-time order processing from phone to admin dashboard",
      "Status workflow: Pending -> Preparing -> Ready -> Delivered / Cancelled",
      "Inventory control with movements (in, out, adjustment) and low stock alerts",
      "Operational dashboard with pending orders, daily totals and revenue",
      "Custom Mediator Pattern with Send/Publish, no MediatR",
      "Pipeline Behaviors for logging and automatic validation",
      "Async messaging via RabbitMQ with publisher and 3 consumers"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "Blazor Server", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "RabbitMQ 7.x", "QRCoder 1.6", "React 19", "TypeScript 5.7", "Vite 6", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture (4 camadas)", "Custom Mediator Pattern", "Pipeline Behavior Pattern", "CQRS (7 commands, 8 queries)", "Domain Events (3 notification types)", "Repository Pattern", "Assembly Scanning via Reflection"],
    endpoints: [
      { method: "GET", path: "/api/menu/{slug}", desc: "Cardapio do restaurante", desc_en: "Restaurant menu" },
      { method: "GET", path: "/api/tables/resolve?token=", desc: "Resolver QR Code da mesa", desc_en: "Resolve table QR Code" },
      { method: "POST", path: "/api/orders", desc: "Criar pedido", desc_en: "Create order" },
      { method: "PUT", path: "/api/orders/{id}/status", desc: "Atualizar status do pedido", desc_en: "Update order status" },
      { method: "GET", path: "/api/dashboard", desc: "Dashboard operacional", desc_en: "Operational dashboard" },
      { method: "POST", path: "/api/stock/movements", desc: "Registrar movimentacao de estoque", desc_en: "Register stock movement" }
    ]
  },
  docforge: {
    name: "RVM.DocForge",
    number: "#04",
    tagline: "Gera documentacao automatica de repositorios C# usando Roslyn, com 7 formatos de saida e snapshots historicos.",
    tagline_en: "Generates automatic documentation from C# repositories using Roslyn, with 7 output formats and historical snapshots.",
    icon: "\ud83d\udcdd",
    color: "#a371f7",
    tests: 30,
    repo: "https://github.com/Elfarrar/RVM.DocForge",
    demo: "https://docforge.lab.rvmtech.com.br",
    tags: ["Roslyn", "Documentation", "Code Analysis", "Markdown", "REST API"],
    description: `RVM.DocForge e um servico API que analisa automaticamente repositorios C# e gera documentacao abrangente. Utiliza Roslyn para analise estatica de codigo, extrai endpoints de API, entidades de dominio e servicos, e entao gera multiplos formatos de documentacao: README, API Reference, Entity Schema, Architecture Overview, Dependency Graph, Service Catalog e Full Documentation. O sistema persiste snapshots de analise e documentos gerados em PostgreSQL para rastreamento historico.`,
    description_en: `RVM.DocForge is an API service that automatically analyzes C# repositories and generates comprehensive documentation. It uses Roslyn for static code analysis, extracts API endpoints, domain entities and services, then generates multiple documentation formats: README, API Reference, Entity Schema, Architecture Overview, Dependency Graph, Service Catalog and Full Documentation. The system persists analysis snapshots and generated documents in PostgreSQL for historical tracking.`,
    features: [
      "Analise automatizada de repositorios usando Roslyn (syntax tree parsing)",
      "Geracao de documentacao em 7 formatos: README, API Reference, Entity Schema, Architecture Overview, Dependency Graph, Service Catalog, Full Documentation",
      "Rastreamento de snapshots com historico de analises",
      "Extracao de endpoints de API com rotas, metodos HTTP e parametros",
      "Descoberta de entidades (classes, records, structs, enums) com propriedades",
      "Catalogo de servicos com assinaturas de metodos e lifetime de DI",
      "Geracao de Markdown com Markdig",
      "Autenticacao por API Key com rate limiting por role"
    ],
    features_en: [
      "Automated repository analysis using Roslyn (syntax tree parsing)",
      "Documentation generation in 7 formats: README, API Reference, Entity Schema, Architecture Overview, Dependency Graph, Service Catalog, Full Documentation",
      "Snapshot tracking with analysis history",
      "API endpoint extraction with routes, HTTP methods and parameters",
      "Entity discovery (classes, records, structs, enums) with properties",
      "Service catalog with method signatures and DI lifetime",
      "Markdown generation with Markdig",
      "API Key authentication with role-based rate limiting"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "Roslyn (Microsoft.CodeAnalysis) 5.0", "Markdig 0.40", "EF Core 10", "PostgreSQL", "Npgsql", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture (3 camadas)", "Strategy Pattern (7 Document Generators)", "Visitor Pattern (CSharpSyntaxWalker)", "Repository Pattern", "Dependency Injection"],
    endpoints: [
      { method: "GET", path: "/api/projects", desc: "Listar projetos", desc_en: "List projects" },
      { method: "POST", path: "/api/projects", desc: "Criar projeto", desc_en: "Create project" },
      { method: "POST", path: "/api/analysis/{projectId}", desc: "Analisar repositorio", desc_en: "Analyze repository" },
      { method: "GET", path: "/api/analysis/snapshots/{id}", desc: "Detalhes do snapshot", desc_en: "Snapshot details" },
      { method: "POST", path: "/api/documents/generate", desc: "Gerar documentacao", desc_en: "Generate documentation" },
      { method: "GET", path: "/api/documents/{id}/raw", desc: "Markdown bruto", desc_en: "Raw Markdown" }
    ]
  },
  healthguard: {
    name: "RVM.HealthGuard",
    number: "#05",
    tagline: "Monitoramento de saude de servicos HTTP com deteccao de incidentes, uptime analytics e notificacoes SignalR.",
    tagline_en: "HTTP service health monitoring with incident detection, uptime analytics and SignalR notifications.",
    icon: "\ud83d\udee1\ufe0f",
    color: "#3fb950",
    tests: 29,
    repo: "https://github.com/Elfarrar/RVM.HealthGuard",
    demo: "https://healthguard.lab.rvmtech.com.br",
    tags: ["Health Monitoring", "SignalR", "Incidents", "Uptime", "Background Service"],
    description: `RVM.HealthGuard e um sistema de monitoramento de saude e gerenciamento de incidentes. Monitora continuamente endpoints HTTP de servicos, rastreia status em tempo real, detecta incidentes (downtime, degradacao, timeout) e fornece analytics historicos detalhados. Utiliza PostgreSQL para persistencia, SignalR para notificacoes em tempo real e Background Services para polling automatico dos endpoints.`,
    description_en: `RVM.HealthGuard is a health monitoring and incident management system. It continuously monitors HTTP service endpoints, tracks real-time status, detects incidents (downtime, degradation, timeout) and provides detailed historical analytics. Uses PostgreSQL for persistence, SignalR for real-time notifications and Background Services for automatic endpoint polling.`,
    features: [
      "Monitoramento HTTP com intervalos e timeouts configuraveis",
      "Rastreamento de status em tempo real: Healthy, Unhealthy, Degraded",
      "Deteccao automatica de incidentes: Down, Degraded, Timeout",
      "Calculo de uptime percentual em janelas de 24 horas",
      "Analytics de tempo medio de resposta",
      "Notificacoes em tempo real via SignalR com agrupamento por servico",
      "HealthCheckWorker como BackgroundService com polling continuo",
      "Historico completo de auditorias de health checks e incidentes",
      "Rate limiting (60 req/min global, 200 req/min por API Key)"
    ],
    features_en: [
      "HTTP monitoring with configurable intervals and timeouts",
      "Real-time status tracking: Healthy, Unhealthy, Degraded",
      "Automatic incident detection: Down, Degraded, Timeout",
      "Uptime percentage calculation in 24-hour windows",
      "Average response time analytics",
      "Real-time notifications via SignalR with service grouping",
      "HealthCheckWorker as BackgroundService with continuous polling",
      "Complete audit history of health checks and incidents",
      "Rate limiting (60 req/min global, 200 req/min per API Key)"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "SignalR", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture (3 camadas)", "Background Service Pattern", "Repository Pattern", "Real-time Push (SignalR Hub)", "Custom Auth Handler", "Middleware Pipeline"],
    endpoints: [
      { method: "GET", path: "/api/services", desc: "Listar servicos monitorados", desc_en: "List monitored services" },
      { method: "POST", path: "/api/services", desc: "Adicionar servico", desc_en: "Add service" },
      { method: "GET", path: "/api/incidents/active", desc: "Incidentes ativos", desc_en: "Active incidents" },
      { method: "GET", path: "/api/status", desc: "Status de todos os servicos", desc_en: "All services status" },
      { method: "GET", path: "/api/status/{id}/history", desc: "Historico de health checks", desc_en: "Health check history" }
    ]
  },
  logstream: {
    name: "RVM.LogStream",
    number: "#06",
    tagline: "Plataforma centralizada de ingestao e busca de logs com retencao configuravel, dashboard SignalR e analytics.",
    tagline_en: "Centralized log ingestion and search platform with configurable retention, SignalR dashboard and analytics.",
    icon: "\ud83d\udcca",
    color: "#f778ba",
    tests: 44,
    repo: "https://github.com/Elfarrar/RVM.LogStream",
    demo: "https://logstream.lab.rvmtech.com.br",
    tags: ["Log Aggregation", "SignalR", "Search", "Retention", "Analytics"],
    description: `RVM.LogStream e uma plataforma centralizada de logs que permite ingestao em batch, busca avancada por multiplos filtros (source, level, query, correlationId, date range), politicas de retencao configuraveis por source e analytics de volume por level/source. O sistema utiliza SignalR para push em tempo real de novos logs e oferece um pipeline completo de observabilidade.`,
    description_en: `RVM.LogStream is a centralized log platform that supports batch ingestion, advanced search with multiple filters (source, level, query, correlationId, date range), configurable retention policies per source and volume analytics by level/source. The system uses SignalR for real-time push of new logs and provides a complete observability pipeline.`,
    features: [
      "Ingestao de logs em batch com auto-criacao de sources",
      "Busca avancada por source, level, query, correlation ID e range de datas",
      "Politicas de retencao configuraveis por source pattern",
      "Limpeza automatica via RetentionWorker (BackgroundService)",
      "Analytics de volume por level e por source",
      "Push de logs em tempo real via SignalR Hub",
      "Suporte a 6 niveis de log: Trace, Debug, Information, Warning, Error, Critical",
      "Paginacao e contagem em todas as queries"
    ],
    features_en: [
      "Batch log ingestion with auto-creation of sources",
      "Advanced search by source, level, query, correlation ID and date range",
      "Configurable retention policies per source pattern",
      "Automatic cleanup via RetentionWorker (BackgroundService)",
      "Volume analytics by level and by source",
      "Real-time log push via SignalR Hub",
      "Support for 6 log levels: Trace, Debug, Information, Warning, Error, Critical",
      "Pagination and counting in all queries"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "SignalR", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture", "Background Service Pattern (RetentionWorker)", "Repository Pattern", "Batch Ingestion Pattern", "Real-time Push (SignalR)"],
    endpoints: [
      { method: "POST", path: "/api/logs/ingest", desc: "Ingestao de logs em batch", desc_en: "Batch log ingestion" },
      { method: "GET", path: "/api/logs/search", desc: "Busca com filtros", desc_en: "Search with filters" },
      { method: "GET", path: "/api/logs/volume/by-level", desc: "Volume por level", desc_en: "Volume by level" },
      { method: "GET", path: "/api/sources", desc: "Listar sources", desc_en: "List sources" },
      { method: "POST", path: "/api/retention", desc: "Criar politica de retencao", desc_en: "Create retention policy" }
    ]
  },
  liveboard: {
    name: "RVM.LiveBoard",
    number: "#07",
    tagline: "Dashboard de monitoramento em tempo real com metricas, alertas configurables, paineis interativos e SignalR.",
    tagline_en: "Real-time monitoring dashboard with metrics, configurable alerts, interactive panels and SignalR.",
    icon: "\ud83d\udcf1",
    color: "#79c0ff",
    tests: 48,
    repo: "https://github.com/Elfarrar/RVM.LiveBoard",
    demo: "https://liveboard.lab.rvmtech.com.br",
    tags: ["Real-time Dashboard", "SignalR", "Metrics", "Alerts", "Aggregation"],
    description: `RVM.LiveBoard e um dashboard de monitoramento em tempo real que permite ingestao de metricas, visualizacao em paineis configuraveis (LineChart, BarChart, Gauge, Counter, Table, Heatmap), regras de alerta com condicoes (gt, gte, lt, lte, eq), severidades (Info, Warning, Critical) e agregacao de dados (Last, Average, Sum, Min, Max, Count). Utiliza SignalR para push de metricas e alertas ao vivo.`,
    description_en: `RVM.LiveBoard is a real-time monitoring dashboard that supports metric ingestion, visualization in configurable panels (LineChart, BarChart, Gauge, Counter, Table, Heatmap), alert rules with conditions (gt, gte, lt, lte, eq), severities (Info, Warning, Critical) and data aggregation (Last, Average, Sum, Min, Max, Count). Uses SignalR for live metric and alert push.`,
    features: [
      "Dashboards com paineis configuraveis em layout de grid (GridColumn/Row/Width/Height)",
      "6 tipos de painel: LineChart, BarChart, Gauge, Counter, Table, Heatmap",
      "Ingestao de metricas com nome, valor e tags",
      "Agregacao de dados: Last, Average, Sum, Min, Max, Count",
      "Regras de alerta com condicoes (gt, gte, lt, lte, eq) e severidades",
      "AlertEvaluationWorker: avalia regras a cada 30 segundos",
      "MetricCleanupWorker: purga metricas antigas automaticamente",
      "SignalR Hub com grupos por dashboard e por metrica",
      "Acknowledge e Resolve de alertas"
    ],
    features_en: [
      "Dashboards with configurable panels in grid layout (GridColumn/Row/Width/Height)",
      "6 panel types: LineChart, BarChart, Gauge, Counter, Table, Heatmap",
      "Metric ingestion with name, value and tags",
      "Data aggregation: Last, Average, Sum, Min, Max, Count",
      "Alert rules with conditions (gt, gte, lt, lte, eq) and severities",
      "AlertEvaluationWorker: evaluates rules every 30 seconds",
      "MetricCleanupWorker: automatically purges old metrics",
      "SignalR Hub with groups per dashboard and per metric",
      "Acknowledge and Resolve alerts"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "SignalR", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture", "Background Service Pattern (2 workers)", "Repository Pattern", "Real-time Push (SignalR Hub Groups)", "Metric Aggregation Engine"],
    endpoints: [
      { method: "POST", path: "/api/metrics/ingest", desc: "Ingerir metricas", desc_en: "Ingest metrics" },
      { method: "GET", path: "/api/metrics/query", desc: "Consultar metricas", desc_en: "Query metrics" },
      { method: "GET", path: "/api/dashboards", desc: "Listar dashboards", desc_en: "List dashboards" },
      { method: "POST", path: "/api/dashboards/{id}/panels", desc: "Adicionar painel", desc_en: "Add panel" },
      { method: "POST", path: "/api/alerts/rules", desc: "Criar regra de alerta", desc_en: "Create alert rule" },
      { method: "PUT", path: "/api/alerts/{id}/acknowledge", desc: "Acknowledge alerta", desc_en: "Acknowledge alert" }
    ]
  },
  shopengine: {
    name: "RVM.ShopEngine",
    number: "#08",
    tagline: "Motor de e-commerce com catalogo, carrinho por sessao, checkout com controle de estoque e ciclo de pagamento.",
    tagline_en: "E-commerce engine with catalog, session-based cart, checkout with stock control and payment lifecycle.",
    icon: "\ud83d\uded2",
    color: "#d29922",
    tests: 42,
    repo: "https://github.com/Elfarrar/RVM.ShopEngine",
    demo: "https://shopengine.lab.rvmtech.com.br",
    tags: ["E-commerce", "Orders", "Payments", "Cart", "Stock Control"],
    description: `RVM.ShopEngine e um motor de e-commerce completo com catalogo de produtos por categorias (com slug), carrinho baseado em sessao, checkout com validacao e decremento automatico de estoque, e ciclo completo de pagamento (Pending -> Authorized -> Captured -> Failed -> Refunded). Suporta multiplos metodos de pagamento (CreditCard, DebitCard, Pix, BankSlip, Wallet) e mantem snapshots dos produtos no momento do pedido.`,
    description_en: `RVM.ShopEngine is a complete e-commerce engine with product catalog by categories (with slug), session-based cart, checkout with validation and automatic stock decrement, and full payment lifecycle (Pending -> Authorized -> Captured -> Failed -> Refunded). Supports multiple payment methods (CreditCard, DebitCard, Pix, BankSlip, Wallet) and maintains product snapshots at order time.`,
    features: [
      "Catalogo de produtos com categorias, slugs, SKU, precos e estoque",
      "Carrinho baseado em SessionId com calculo automatico de total",
      "Checkout: cria Order a partir do Cart com validacao de estoque e decremento atomico",
      "Geracao automatica de OrderNumber",
      "Snapshot de produto no momento do pedido (preco, nome salvos no OrderItem)",
      "Ciclo de vida do pedido: Pending -> Confirmed -> Processing -> Shipped -> Delivered / Cancelled / Refunded",
      "Ciclo de pagamento: Pending -> Authorized -> Captured -> Failed -> Refunded",
      "5 metodos de pagamento: CreditCard, DebitCard, Pix, BankSlip, Wallet",
      "Busca de produtos com filtros por query, categoria e status ativo"
    ],
    features_en: [
      "Product catalog with categories, slugs, SKU, prices and stock",
      "Session-based cart with automatic total calculation",
      "Checkout: creates Order from Cart with stock validation and atomic decrement",
      "Automatic OrderNumber generation",
      "Product snapshot at order time (price, name saved in OrderItem)",
      "Order lifecycle: Pending -> Confirmed -> Processing -> Shipped -> Delivered / Cancelled / Refunded",
      "Payment lifecycle: Pending -> Authorized -> Captured -> Failed -> Refunded",
      "5 payment methods: CreditCard, DebitCard, Pix, BankSlip, Wallet",
      "Product search with filters by query, category and active status"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture", "Repository Pattern", "Service Layer (OrderService, PaymentService)", "Domain Entity with Lifecycle (Order, Payment)", "Session-Based Cart"],
    endpoints: [
      { method: "GET", path: "/api/products", desc: "Buscar produtos", desc_en: "Search products" },
      { method: "GET", path: "/api/categories", desc: "Listar categorias", desc_en: "List categories" },
      { method: "GET", path: "/api/cart/{sessionId}", desc: "Ver carrinho", desc_en: "View cart" },
      { method: "POST", path: "/api/cart/{sessionId}/items", desc: "Adicionar ao carrinho", desc_en: "Add to cart" },
      { method: "POST", path: "/api/orders", desc: "Criar pedido do carrinho", desc_en: "Create order from cart" },
      { method: "POST", path: "/api/payments/{orderId}/capture", desc: "Capturar pagamento", desc_en: "Capture payment" }
    ]
  },
  nearby: {
    name: "RVM.NearBy",
    number: "#09",
    tagline: "Rede social baseada em localizacao com feed por proximidade, posts geolocalizados, likes, comentarios e places.",
    tagline_en: "Location-based social network with proximity feed, geolocated posts, likes, comments and places.",
    icon: "\ud83d\udccd",
    color: "#f85149",
    tests: 45,
    repo: "https://github.com/Elfarrar/RVM.NearBy",
    demo: "https://nearby.lab.rvmtech.com.br",
    tags: ["Geolocation", "Social Network", "Haversine", "Feed", "Proximity"],
    description: `RVM.NearBy e uma rede social baseada em localizacao onde usuarios criam posts geolocalizados visiveis por proximidade. O feed principal exibe posts proximos usando a formula de Haversine para calculo de distancia. Suporta tres niveis de visibilidade (Public, NearbyOnly, Private), midia anexada (Image, Video, Audio), likes, comentarios, e Places (pontos de interesse) com busca por proximidade.`,
    description_en: `RVM.NearBy is a location-based social network where users create geolocated posts visible by proximity. The main feed displays nearby posts using the Haversine formula for distance calculation. Supports three visibility levels (Public, NearbyOnly, Private), attached media (Image, Video, Audio), likes, comments, and Places (points of interest) with proximity search.`,
    features: [
      "Feed de posts por proximidade usando formula de Haversine",
      "Bounding box pre-filtro + calculo preciso de distancia em km",
      "3 niveis de visibilidade: Public, NearbyOnly, Private",
      "Posts com midia anexada (Image, Video, Audio) com ordenacao",
      "Sistema de likes com contagem em tempo real no post",
      "Comentarios com contagem sincronizada no post",
      "Places (pontos de interesse) com busca por nome/categoria e proximidade",
      "Perfis de usuario com localizacao atualizada em tempo real",
      "Feed recente (posts publicos) e feed nearby (posts proximos)"
    ],
    features_en: [
      "Proximity-based post feed using Haversine formula",
      "Bounding box pre-filter + precise distance calculation in km",
      "3 visibility levels: Public, NearbyOnly, Private",
      "Posts with attached media (Image, Video, Audio) with ordering",
      "Like system with real-time count on post",
      "Comments with synchronized count on post",
      "Places (points of interest) with name/category and proximity search",
      "User profiles with real-time location updates",
      "Recent feed (public posts) and nearby feed (proximity posts)"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "EF Core 10", "PostgreSQL", "Npgsql 10.0.1", "Serilog", "xUnit", "Moq"],
    patterns: ["Clean Architecture", "Repository Pattern", "Haversine Distance Calculation", "Bounding Box Pre-filter", "Service Layer (FeedService)", "Denormalized Counters (LikeCount, CommentCount)"],
    endpoints: [
      { method: "GET", path: "/api/feed/nearby", desc: "Feed por proximidade", desc_en: "Proximity feed" },
      { method: "GET", path: "/api/feed/recent", desc: "Feed recente", desc_en: "Recent feed" },
      { method: "POST", path: "/api/posts", desc: "Criar post geolocalizado", desc_en: "Create geolocated post" },
      { method: "POST", path: "/api/posts/{id}/like", desc: "Curtir post", desc_en: "Like post" },
      { method: "POST", path: "/api/posts/{id}/comments", desc: "Comentar post", desc_en: "Comment on post" },
      { method: "GET", path: "/api/places/nearby", desc: "Places proximos", desc_en: "Nearby places" }
    ]
  },
  mcpforge: {
    name: "RVM.McpForge",
    number: "#10",
    tagline: "Plataforma de analise de codigo e geracao automatica de servidores MCP para integracao com assistentes de IA.",
    tagline_en: "Code analysis platform and automatic MCP server generation for AI assistant integration.",
    icon: "\u2699\ufe0f",
    color: "#56d364",
    tests: 6,
    repo: "https://github.com/Elfarrar/RVM.McpForge",
    demo: "https://mcpforge.lab.rvmtech.com.br",
    tags: ["MCP Protocol", "Roslyn", "Code Generation", "Scriban", "Database Introspection"],
    description: `RVM.McpForge e uma plataforma inteligente de analise de codigo e geracao de servidores MCP (Model Context Protocol) para projetos .NET. Analisa repositorios C# via Roslyn ou bancos PostgreSQL por introspecao, extrai endpoints, entidades, servicos e tabelas, e gera automaticamente servidores MCP com tools e resources para integracao com assistentes de IA. Suporta dois tipos de fonte (Git e Database), rastreia status do projeto e persiste snapshots de analise em PostgreSQL.`,
    description_en: `RVM.McpForge is an intelligent code analysis and MCP (Model Context Protocol) server generation platform for .NET projects. It analyzes C# repositories via Roslyn or PostgreSQL databases via introspection, extracts endpoints, entities, services and tables, then automatically generates MCP servers with tools and resources for AI assistant integration. Supports two source types (Git and Database), tracks project status and persists analysis snapshots in PostgreSQL.`,
    features: [
      "Analise dual: repositorios Git (C#) e bancos PostgreSQL",
      "Analise estatica com Roslyn: extrai controllers, endpoints, entidades e servicos",
      "Introspecao de banco: descobre tabelas, colunas, constraints e relacionamentos",
      "Geracao automatica de MCP tools a partir de endpoints e tabelas descobertos",
      "Clonagem automatica de repositorios Git publicos via LibGit2Sharp",
      "Ciclo de vida do projeto: Pending -> Analyzing -> Analyzed -> Generating -> Ready",
      "Snapshots de analise com historico persistido",
      "Categorizacao de tools: Query, Command, Schema",
      "Dashboard Blazor Server com gerenciamento de projetos e servidores gerados",
      "Geracao de codigo com templates Scriban"
    ],
    features_en: [
      "Dual analysis: Git repositories (C#) and PostgreSQL databases",
      "Static analysis with Roslyn: extracts controllers, endpoints, entities and services",
      "Database introspection: discovers tables, columns, constraints and relationships",
      "Automatic MCP tool generation from discovered endpoints and tables",
      "Automatic Git repository cloning via LibGit2Sharp",
      "Project lifecycle: Pending -> Analyzing -> Analyzed -> Generating -> Ready",
      "Analysis snapshots with persisted history",
      "Tool categorization: Query, Command, Schema",
      "Blazor Server dashboard with project and generated server management",
      "Code generation with Scriban templates"
    ],
    technologies: [".NET 10", "ASP.NET Core 10", "Roslyn (Microsoft.CodeAnalysis) 4.13", "Scriban 5.12", "LibGit2Sharp 0.30", "EF Core 10", "PostgreSQL", "Npgsql", "Blazor Server", "Serilog", "xUnit"],
    patterns: ["Layered Architecture (4 camadas)", "Orchestrator Pattern (ForgeOrchestrator)", "Strategy Pattern (ISourceAnalyzer)", "Visitor Pattern (SyntaxWalkers)", "Repository Pattern", "Custom Auth Handler (API Key)"],
    endpoints: [
      { method: "GET", path: "/api/forge/projects", desc: "Listar projetos", desc_en: "List projects" },
      { method: "POST", path: "/api/forge/projects", desc: "Criar projeto", desc_en: "Create project" },
      { method: "POST", path: "/api/forge/projects/{id}/analyze", desc: "Analisar projeto", desc_en: "Analyze project" },
      { method: "POST", path: "/api/forge/projects/{id}/generate", desc: "Gerar servidor MCP", desc_en: "Generate MCP server" },
      { method: "GET", path: "/api/forge/generated/{projectId}", desc: "Servidores gerados", desc_en: "Generated servers" },
      { method: "DELETE", path: "/api/forge/projects/{id}", desc: "Remover projeto", desc_en: "Delete project" }
    ]
  }
};
